### ISSUE TITLE
flit dependency on Pygments

### ISSUE THREAD

**Issue by philbarker** [tombaker/csv2shex#5]
On following the installation instructions I got:
```
$ flit install -s
Fetching list of valid trove classifiers                                             I-flit.validate
The file description seems not to be valid rst for PyPI; it will be interpreted as plain text  E-flit.validate
<string>:16: (WARNING/2) Cannot analyze code. Pygments package not found.
           E-flit.validate
Invalid config values (see log)
```

fixed when I ran `pip install Pygments` and re-ran flit.

**Comment by dcmi** [comment]
@philbarker Thank you for pointing this out! I have [added Pygments as a dependency to the pyproject.toml file](https://github.com/tombaker/csv2shex/commit/f1dbb9cbdbb0c9c6ee41e153546b78ffbc97cbe0).

**Comment by philbarker** [comment]
That doesn't seem to solve the problem. (I guess because it is `flit install -s` that requires  Pygments, so it doesn't get as far as reading pyproject.toml?)

Suggest you change to installation instructions to 
```
$ git clone https://github.com/tombaker/csv2shex.git
$ cd csv2shex
$ python -m venv .venv
$ source .venv/bin/activate
$ pip install flit Pygments
$ flit install -s
```

**Comment by tombaker** [comment]
@philbarker Thank you, Phil! I had just now reached that very conclusion.

I have [changed the installation instructions](https://github.com/tombaker/csv2shex/commit/f711c6984c2f7d74f4db899fbd59e696bec9e04b) as you suggest, with one difference: I have read in several places that `python3 -m pip` is safer than just plain `pip` because it ensures that pip will use the correct Python.
